package selenium.testcase;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WorkTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void workTest() {
    driver.get("https://work.weixin.qq.com/");
    driver.manage().window().setSize(new Dimension(1050, 685));
    driver.findElement(By.linkText("企业登录")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".js_explore_showApps > .index_explore_item_desc"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    driver.findElement(By.linkText("添加成员")).click();
    js.executeScript("window.scrollTo(0,185)");
    driver.findElement(By.cssSelector(".member_edit_cover > .member_edit_item_right")).click();
    driver.findElement(By.id("username")).click();

  }
}
